name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*'  # Wird ausgelöst, wenn ein Tag mit 'v' beginnt, z.B. v1.0.0

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          logout: false

      - name: Build and push dashboard
        uses: docker/build-push-action@v5
        with:
          context: ./agriNode-dashboard
          file: ./agriNode-dashboard/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/agrinode-dashboard:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/agrinode-dashboard:${{ env.VERSION }}
          build-args: |
            VITE_API_URL=/api
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/agrinode-dashboard:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/agrinode-dashboard:buildcache,mode=max

      - name: Build and push gateway
        uses: docker/build-push-action@v5
        with:
          context: ./agriNode-gateway
          file: ./agriNode-gateway/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/agrinode-gateway:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/agrinode-gateway:${{ env.VERSION }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/agrinode-gateway:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/agrinode-gateway:buildcache,mode=max

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.VERSION }}
          body: |
            ## AgriNode ${{ env.VERSION }}

            Release Notes:
            
            Docker Images für diese Version:
            
            ### Dashboard (Frontend)
            - Docker Hub: [${{ secrets.DOCKER_HUB_USERNAME }}/agrinode-dashboard:${{ env.VERSION }}](https://hub.docker.com/r/${{ secrets.DOCKER_HUB_USERNAME }}/agrinode-dashboard/tags?name=${{ env.VERSION }})
            - `docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/agrinode-dashboard:${{ env.VERSION }}`
            
            ### Gateway (Backend)
            - Docker Hub: [${{ secrets.DOCKER_HUB_USERNAME }}/agrinode-gateway:${{ env.VERSION }}](https://hub.docker.com/r/${{ secrets.DOCKER_HUB_USERNAME }}/agrinode-gateway/tags?name=${{ env.VERSION }})
            - `docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/agrinode-gateway:${{ env.VERSION }}` 
          generate_release_notes: true
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}